site_name: Python Notes
repo_url: https://github.com/songzhenhe/python-note
site_author: 'songzhenhe'
copyright: '2020, songzhenhe'
theme: 
    # name: readthedocs
    # name: mkdocs
    name: material
    
markdown_extensions:
    - toc:
        permalink: true
    - pymdownx.arithmatex

extra_javascript:
    - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
    
nav:
    - Home: index.md
    - Basic: 
      - Data Type: basic/datatype.md
      - RegEx: basic/re.md
      - File: basic/file.md
      - Buildin Functions: basic/buildin.md
    - Intermediate: 
      - Typing: intermediate/typing.md
      - Collections: intermediate/collections.md
      - Lambdas: intermediate/lambdas.md
      - Enumerate: intermediate/enumerate.md
      - Decorators: intermediate/decorators.md
      - Generators: intermediate/generators.md
      - Advanced File: intermediate/file.md
      - Comprehensions: intermediate/comprehensions.md
    - Module: 
      - Pandas: module/pandas.md
      - Pandoc: module/pandoc.md
      - Mkdocs: module/mkdocs.md
      - Geospatial: module/geo.md
